name: Travelnation
description: "Destination App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter_svg: ^2.0.10+1
  flutter_animate: ^4.5.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  google_nav_bar: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  sqflite: ^2.3.3+1

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

  fonts:
   - family: Montserrat
     fonts: 
     - asset: fonts/Montserrat-Bold.ttf
     - weight: 700 
     - asset: fonts/Montserrat-Semibold.ttf
     - weight: 600 
     - asset: fonts/Montserrat-Medium.ttf
     - weight: 500 
     - asset: fonts/Montserrat-Regular.ttf
     - weight: 400 
     - asset: fonts/Montserrat-Light.ttf
     - weight: 300